package com.github.stormwyrm.router.compiler.util;

public class Consts {
    public static final String SEPARATION = "$$";
    public static final String PROJECT = "Router";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE! IT WAS GENERATED BY ROUTER";

    //LOG
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler-> ";

    //Options of processor
    public static final String KEY_MODULE_NAME = "ROUTER_MODULE_NAME";

    //custom interface
    public static final String PACKAGE_NAME = "com.github.stormwyrm.router.";
    public static final String I_AUTOWIRED_INITIALIZER = PACKAGE_NAME + "initializer.IAutowiredInitializer";
    public static final String I_ROUTER_INITIALIZER = PACKAGE_NAME +"initializer.IRouterInitializer";
    public static final String ROUTER = PACKAGE_NAME +"Router";

    //system interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String PARCELABLE = "android.os.Parcelable";
    public static final String BUNDLE = "android.os.Bundle";

    // Java type
    private static final String LANG = "java.lang";
    public static final String BYTE = LANG + ".Byte";
    public static final String SHORT = LANG + ".Short";
    public static final String INTEGER = LANG + ".Integer";
    public static final String LONG = LANG + ".Long";
    public static final String FLOAT = LANG + ".Float";
    public static final String DOUBEL = LANG + ".Double";
    public static final String BOOLEAN = LANG + ".Boolean";
    public static final String CHAR = LANG + ".Character";
    public static final String STRING = LANG + ".String";
    public static final String SERIALIZABLE = "java.io.Serializable";
}
